services:
  postgres:
    image: postgres:17
    container_name: postgres_books
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - '5432:5432'
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
